version: '3'
services: 
  viz:
    image: dockersamples/visualizer
    deploy:
      placement:
        constraints: 
          - "node.role == manager"
    mode: global
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  nodenamer:
    image: lrakai/nodenamer:1.0.1
    deploy:
      replicas: 6
      placement:
        constraints: 
          - "node.labels.zone != 1"
        preferences:
          - spread: node.labels.zone
    ports:
      - "80:80"