version: '3'
services: 
  viz:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: 
          - "node.role == manager"
  nodenamer:
    image: lrakai/nodenamer:1.0.1
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "80:80"
    deploy:
      replicas: 6